//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSIGNMENT_CLASS_LEVEL
    {
        public long Assignment_Class_Level_Id { get; set; }
        public long Assignment_Id { get; set; }
        public int Class_Level_Id { get; set; }
    
        public virtual ASSIGNMENT ASSIGNMENT { get; set; }
        public virtual CLASS_LEVEL CLASS_LEVEL { get; set; }
    }
}
