//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSIGNMENT
    {
        public ASSIGNMENT()
        {
            this.ASSIGNMENT_CLASS_LEVEL = new HashSet<ASSIGNMENT_CLASS_LEVEL>();
            this.ASSIGNMENT_GRADING = new HashSet<ASSIGNMENT_GRADING>();
        }
    
        public long Assignment_Id { get; set; }
        public string Assignment_Topic { get; set; }
        public string Assignment_Description { get; set; }
        public long Staff_id { get; set; }
        public int Class_Level_Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> Date_Due { get; set; }
        public string Attached_File_Link { get; set; }
        public bool Active { get; set; }
        public int Subject_Id { get; set; }
    
        public virtual CLASS_LEVEL CLASS_LEVEL { get; set; }
        public virtual ICollection<ASSIGNMENT_CLASS_LEVEL> ASSIGNMENT_CLASS_LEVEL { get; set; }
        public virtual ICollection<ASSIGNMENT_GRADING> ASSIGNMENT_GRADING { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
