//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEHAVIOUR
    {
        public BEHAVIOUR()
        {
            this.BEHAVIOUR_GRADING = new HashSet<BEHAVIOUR_GRADING>();
            this.RESULT = new HashSet<RESULT>();
        }
    
        public int Behaviour_Id { get; set; }
        public string Behaviour_Name { get; set; }
    
        public virtual ICollection<BEHAVIOUR_GRADING> BEHAVIOUR_GRADING { get; set; }
        public virtual ICollection<RESULT> RESULT { get; set; }
    }
}
