//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_LEVEL
    {
        public CLASS_LEVEL()
        {
            this.ASSIGNMENT = new HashSet<ASSIGNMENT>();
            this.ASSIGNMENT_CLASS_LEVEL = new HashSet<ASSIGNMENT_CLASS_LEVEL>();
        }
    
        public int Class_Level_Id { get; set; }
        public int Level_Id { get; set; }
        public int Class_Id { get; set; }
    
        public virtual ICollection<ASSIGNMENT> ASSIGNMENT { get; set; }
        public virtual ICollection<ASSIGNMENT_CLASS_LEVEL> ASSIGNMENT_CLASS_LEVEL { get; set; }
        public virtual CLASS CLASS { get; set; }
        public virtual LEVEL LEVEL { get; set; }
    }
}
