//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class School_DbEntities : DbContext
    {
        public School_DbEntities()
            : base("name=School_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BEHAVIOUR> BEHAVIOUR { get; set; }
        public virtual DbSet<BLOOD_GROUP> BLOOD_GROUP { get; set; }
        public virtual DbSet<CLASS> CLASS { get; set; }
        public virtual DbSet<CLASS_LEVEL> CLASS_LEVEL { get; set; }
        public virtual DbSet<CONTINUOUS_ASSESSMENT> CONTINUOUS_ASSESSMENT { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<FEE> FEE { get; set; }
        public virtual DbSet<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual DbSet<FEE_TYPE> FEE_TYPE { get; set; }
        public virtual DbSet<GENOTYPE> GENOTYPE { get; set; }
        public virtual DbSet<LEVEL> LEVEL { get; set; }
        public virtual DbSet<LOCAL_GOVERNMENT> LOCAL_GOVERNMENT { get; set; }
        public virtual DbSet<NATIONALITY> NATIONALITY { get; set; }
        public virtual DbSet<PARENT> PARENT { get; set; }
        public virtual DbSet<PARENT_STUDENT> PARENT_STUDENT { get; set; }
        public virtual DbSet<PAYMENT> PAYMENT { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PERSON_TYPE> PERSON_TYPE { get; set; }
        public virtual DbSet<RELIGION> RELIGION { get; set; }
        public virtual DbSet<RESULT> RESULT { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<SESSION> SESSION { get; set; }
        public virtual DbSet<SESSION_TERM> SESSION_TERM { get; set; }
        public virtual DbSet<SEX> SEX { get; set; }
        public virtual DbSet<SKILL> SKILL { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
        public virtual DbSet<STAFF_TYPE> STAFF_TYPE { get; set; }
        public virtual DbSet<STATE> STATE { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<STUDENT_CATEGORY> STUDENT_CATEGORY { get; set; }
        public virtual DbSet<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
        public virtual DbSet<STUDENT_REGISTRATION_NUMBER_ASSIGNMENT> STUDENT_REGISTRATION_NUMBER_ASSIGNMENT { get; set; }
        public virtual DbSet<STUDENT_STATUS> STUDENT_STATUS { get; set; }
        public virtual DbSet<SUBJECT> SUBJECT { get; set; }
        public virtual DbSet<SUBJECT_LEVEL> SUBJECT_LEVEL { get; set; }
        public virtual DbSet<TEACHER_CLASS_ALLOCATION> TEACHER_CLASS_ALLOCATION { get; set; }
        public virtual DbSet<TERM> TERM { get; set; }
        public virtual DbSet<TITLE> TITLE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
