//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_TYPE
    {
        public FEE_TYPE()
        {
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.PAYMENT = new HashSet<PAYMENT>();
        }
    
        public int Fee_Type_Id { get; set; }
        public string Fee_Type_Name { get; set; }
        public string Fee_Type_Description { get; set; }
    
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
    }
}
