//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARENT_VERIFICATION
    {
        public long Parent_Verification_Id { get; set; }
        public long Student_Id { get; set; }
        public string Verification_Detail { get; set; }
        public bool Verified { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
