//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public long Payment_Id { get; set; }
        public long Person_Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public System.DateTime Date_Paid { get; set; }
        public int Session_Id { get; set; }
        public int Person_Type_Id { get; set; }
    
        public virtual FEE_TYPE FEE_TYPE { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
