//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
            this.STAFF = new HashSet<STAFF>();
            this.STUDENT = new HashSet<STUDENT>();
            this.USER = new HashSet<USER>();
        }
    
        public long Person_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Initial { get; set; }
        public string Title { get; set; }
        public string Image_File_Url { get; set; }
        public string Signature_File_Url { get; set; }
        public byte Sex_Id { get; set; }
        public string Contact_Address { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string State_Id { get; set; }
        public Nullable<int> Local_Government_Id { get; set; }
        public string Home_Town { get; set; }
        public string Home_Address { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public Nullable<int> Nationality_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public Nullable<int> Blood_Group_Id { get; set; }
        public Nullable<int> Genotype_Id { get; set; }
        public System.DateTime Date_Entered { get; set; }
    
        public virtual BLOOD_GROUP BLOOD_GROUP { get; set; }
        public virtual GENOTYPE GENOTYPE { get; set; }
        public virtual LOCAL_GOVERNMENT LOCAL_GOVERNMENT { get; set; }
        public virtual NATIONALITY NATIONALITY { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual RELIGION RELIGION { get; set; }
        public virtual SEX SEX { get; set; }
        public virtual STATE STATE { get; set; }
        public virtual ICollection<STAFF> STAFF { get; set; }
        public virtual ICollection<STUDENT> STUDENT { get; set; }
        public virtual ICollection<USER> USER { get; set; }
    }
}
