//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_TYPE
    {
        public PERSON_TYPE()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
            this.PERSON = new HashSet<PERSON>();
        }
    
        public int Person_Type_Id { get; set; }
        public string Person_Type_Name { get; set; }
        public string Person_Type_Description { get; set; }
    
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual ICollection<PERSON> PERSON { get; set; }
    }
}
