//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATIONSHIP
    {
        public RELATIONSHIP()
        {
            this.PARENT = new HashSet<PARENT>();
        }
    
        public int Relationship_Id { get; set; }
        public string Relationship_Name { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<PARENT> PARENT { get; set; }
    }
}
