//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION
    {
        public SESSION()
        {
            this.BEHAVIOUR_GRADING = new HashSet<BEHAVIOUR_GRADING>();
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.PAYMENT = new HashSet<PAYMENT>();
            this.RESULT = new HashSet<RESULT>();
            this.SESSION_TERM = new HashSet<SESSION_TERM>();
            this.STUDENT_LEVEL = new HashSet<STUDENT_LEVEL>();
            this.STUDENT_REGISTRATION_NUMBER_ASSIGNMENT = new HashSet<STUDENT_REGISTRATION_NUMBER_ASSIGNMENT>();
            this.TEACHER_SUBJECT_ALLOCATION = new HashSet<TEACHER_SUBJECT_ALLOCATION>();
        }
    
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<BEHAVIOUR_GRADING> BEHAVIOUR_GRADING { get; set; }
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual ICollection<RESULT> RESULT { get; set; }
        public virtual ICollection<SESSION_TERM> SESSION_TERM { get; set; }
        public virtual ICollection<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
        public virtual ICollection<STUDENT_REGISTRATION_NUMBER_ASSIGNMENT> STUDENT_REGISTRATION_NUMBER_ASSIGNMENT { get; set; }
        public virtual ICollection<TEACHER_SUBJECT_ALLOCATION> TEACHER_SUBJECT_ALLOCATION { get; set; }
    }
}
