//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION_TERM
    {
        public int Session_Term_Id { get; set; }
        public int Session_Id { get; set; }
        public int Term_Id { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public bool Active { get; set; }
    
        public virtual SESSION SESSION { get; set; }
        public virtual TERM TERM { get; set; }
    }
}
