//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEX
    {
        public SEX()
        {
            this.PARENT = new HashSet<PARENT>();
            this.PERSON = new HashSet<PERSON>();
        }
    
        public byte Sex_Id { get; set; }
        public string Sex_Name { get; set; }
    
        public virtual ICollection<PARENT> PARENT { get; set; }
        public virtual ICollection<PERSON> PERSON { get; set; }
    }
}
