//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILL
    {
        public SKILL()
        {
            this.RESULT = new HashSet<RESULT>();
        }
    
        public int Skill_Id { get; set; }
        public Nullable<int> Handwriting { get; set; }
        public Nullable<int> Fluency { get; set; }
        public Nullable<int> Games { get; set; }
        public Nullable<int> Sport { get; set; }
        public Nullable<int> Gymnastics { get; set; }
        public Nullable<int> Drawing { get; set; }
        public Nullable<int> Crafts { get; set; }
        public Nullable<int> Music { get; set; }
    
        public virtual ICollection<RESULT> RESULT { get; set; }
    }
}
