//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.ASSIGNMENT = new HashSet<ASSIGNMENT>();
            this.TEACHER_SUBJECT_ALLOCATION = new HashSet<TEACHER_SUBJECT_ALLOCATION>();
        }
    
        public long Staff_Id { get; set; }
        public int Staff_Type_Id { get; set; }
        public long User_Id { get; set; }
        public Nullable<long> Person_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_name { get; set; }
        public string Other_Names { get; set; }
    
        public virtual ICollection<ASSIGNMENT> ASSIGNMENT { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual STAFF_TYPE STAFF_TYPE { get; set; }
        public virtual USER USER { get; set; }
        public virtual ICollection<TEACHER_SUBJECT_ALLOCATION> TEACHER_SUBJECT_ALLOCATION { get; set; }
    }
}
