//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public STUDENT()
        {
            this.BEHAVIOUR_GRADING = new HashSet<BEHAVIOUR_GRADING>();
            this.PARENT_STUDENT = new HashSet<PARENT_STUDENT>();
            this.PARENT_VERIFICATION = new HashSet<PARENT_VERIFICATION>();
            this.RESULT = new HashSet<RESULT>();
            this.STUDENT_LEVEL = new HashSet<STUDENT_LEVEL>();
        }
    
        public long Student_Id { get; set; }
        public string Reg_No { get; set; }
        public long User_Id { get; set; }
        public int Student_Category_Id { get; set; }
        public int Student_Status_Id { get; set; }
        public string Parent_Phone { get; set; }
        public string Parent_Email { get; set; }
        public Nullable<long> Person_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Names { get; set; }
    
        public virtual ICollection<BEHAVIOUR_GRADING> BEHAVIOUR_GRADING { get; set; }
        public virtual ICollection<PARENT_STUDENT> PARENT_STUDENT { get; set; }
        public virtual ICollection<PARENT_VERIFICATION> PARENT_VERIFICATION { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<RESULT> RESULT { get; set; }
        public virtual ICollection<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
        public virtual STUDENT_CATEGORY STUDENT_CATEGORY { get; set; }
        public virtual STUDENT_STATUS STUDENT_STATUS { get; set; }
        public virtual USER USER { get; set; }
    }
}
