//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_REGISTRATION_NUMBER_ASSIGNMENT
    {
        public int Class_Id { get; set; }
        public int Level_Id { get; set; }
        public int Session_Id { get; set; }
        public int Reg_Serial_Number_Start_From { get; set; }
        public string Reg_Number_Start_From { get; set; }
        public bool Used { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
