//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBJECT
    {
        public SUBJECT()
        {
            this.ASSIGNMENT = new HashSet<ASSIGNMENT>();
            this.RESULT = new HashSet<RESULT>();
            this.SUBJECT_LEVEL = new HashSet<SUBJECT_LEVEL>();
            this.TEACHER_SUBJECT_ALLOCATION = new HashSet<TEACHER_SUBJECT_ALLOCATION>();
        }
    
        public int Subject_Id { get; set; }
        public string Subject_Name { get; set; }
    
        public virtual ICollection<ASSIGNMENT> ASSIGNMENT { get; set; }
        public virtual ICollection<RESULT> RESULT { get; set; }
        public virtual ICollection<SUBJECT_LEVEL> SUBJECT_LEVEL { get; set; }
        public virtual ICollection<TEACHER_SUBJECT_ALLOCATION> TEACHER_SUBJECT_ALLOCATION { get; set; }
    }
}
