//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER_SUBJECT_ALLOCATION
    {
        public int Teacher_Subject_Allocation_Id { get; set; }
        public long Staff_Id { get; set; }
        public int Level_Id { get; set; }
        public int Class_Id { get; set; }
        public int Session_Id { get; set; }
        public bool Activated { get; set; }
        public int SubJect_Id { get; set; }
    
        public virtual CLASS CLASS { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
