//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSchool.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERM
    {
        public TERM()
        {
            this.BEHAVIOUR_GRADING = new HashSet<BEHAVIOUR_GRADING>();
            this.RESULT = new HashSet<RESULT>();
            this.SESSION_TERM = new HashSet<SESSION_TERM>();
        }
    
        public int Term_Id { get; set; }
        public string Term_Name { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<BEHAVIOUR_GRADING> BEHAVIOUR_GRADING { get; set; }
        public virtual ICollection<RESULT> RESULT { get; set; }
        public virtual ICollection<SESSION_TERM> SESSION_TERM { get; set; }
    }
}
